 steps:
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'beta'
   - 'run'
   - 'deploy'
   - 'onlybans-draft'
   - '--source'
   - '.'
   - '--region'
   - 'europe-west1'
   - '--execution-environment'
   - 'gen2'
   - '--allow-unauthenticated'
   - '--service-account'
   - 'onlybans-identity'
   - '--update-env-vars'
   - 'BUCKET=onlybans'
 images:
 - 'gcr.io/eco-groove-292315/onlybans-draft:$COMMIT_SHA'