 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/eco-groove-292315/onlybans-draft:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/eco-groove-292315/onlybans-draft:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'beta'
   - 'run'
   - 'deploy'
   - 'onlybans-draft'
   - '--image'
   - 'gcr.io/eco-groove-292315/onlybans-draft:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
   - '--execution-environment'
   - 'gen2'
   - '--allow-unauthenticated'
   - '--service-account'
   - 'onlybans-identity'
   - '--update-env-vars'
   - 'BUCKET=onlybans'
 images:
 - 'gcr.io/eco-groove-292315/onlybans-draft:$COMMIT_SHA'